### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dancan254**
Corrected some grammatical errors plus some few modifications

### CODE REVIEW

**Comment by divin3circle** [comment]
Nice update however, on the voting process it's not the UI that's responsible for updating the vote tally, it only shows the updated tally. I'll approve the request but consider making the said changes.

**Review by divin3circle — CHANGES_REQUESTED** [review]
UI doesn't update the vote tally. Revert to previous or make the necessary change.

**Comment by Dancan254** [comment]
On it, thanks for the correction

**Review by divin3circle — APPROVED** [review]
Nice job🚀!

**Pull request merged**
